[package]
name = "npm_package_cheker"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
chrono = "0.4.42"
reqwest = { version = "0.12.23", features = ["blocking"] }
serde = "1.0.225"
serde_json = "1.0.145"
